title: My First Webpage
author: rthomas888
email: randy.thomas.home@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Brand new to GitHub.

# social links
# twitter_username: your-twitter-handle
github_username:  rthomas888

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
